### PR TITLE
Completed Write About Section Content #7

### PR DESCRIPTION
**Pull request by Prince-Vijay-Santhosh**
Added the information as provided:
@Prince-Vijay-Santhosh Provide a concise introduction, key feature. Keep it engaging, well-edited and visually appealing for users. Append this content to the about section of the application, fostering trust and user engagement.

### CODE REVIEW

**Comment by Shubhankar84** [comment]
@Prince-Vijay-Santhosh  update in html file itself not in about.md file

**Comment by Prince-Vijay-Santhosh** [comment]
@Shubhankar84 In the project file or create a new HTML file

**Comment by Shubhankar84** [comment]
@Prince-Vijay-Santhosh In the project html file itself

**Comment by Prince-Vijay-Santhosh** [comment]
Completed the work

**Comment by Shubhankar84** [comment]
@Prince-Vijay-Santhosh Make sure that you are making the pull request correctly don't just upload files.

**Comment by Prince-Vijay-Santhosh** [comment]
@Shubhankar84 can I know why did you closed this, I was working on it. I'm new to open-source contribution and trying to learn to pull requests and git.

**Comment by Shubhankar84** [comment]
@Prince-Vijay-Santhosh you can still work on this issue. Issue is not closed and also assigned to you, you can make pull request after you are done with work.

**Pull request closed without merging**
